version: '3'

services:
  db:
    build: ./db
    container_name: db
    hostname: db
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password
    restart: always

  app:
    build: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && node index.js"
    hostname: app
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    depends_on:
      - db
    restart: on-failure

  nginx:
    build: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
      - '8080:80'
    depends_on:
      - app
